name: Server Release

on:
  push:
    tags:        
      - jornet-server-v**

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git checkout -b release-clever
          
      - name: install tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli
          sudo apt-get install -y binaryen

      - name: build wasm demo
        run: |
          cargo build --profile wasm-release --target wasm32-unknown-unknown --example whac-a-square
          wasm-bindgen --out-dir wasm --out-name demo_leaderboard --target web target/wasm32-unknown-unknown/wasm-release/examples/whac-a-square.wasm
          wasm-opt -Oz wasm/demo_leaderboard_bg.wasm --output wasm/demo_leaderboard_o_bg-opt.wasm
          cp -r bevy-jornet/assets jornet-server-ui/public/
          cp wasm/demo_leaderboard_bg-opt.wasm jornet-server-ui/public/demo_leaderboard_bg.wasm
          cp wasm/demo_leaderboard.js jornet-server-ui/public/

      - name: remove Bevy plugin
        run: |
          rm -rf bevy-jornet
          cargo new --lib bevy-jornet
          cargo update
          git add bevy-jornet
          git add Cargo.lock
          git commit --message "remove Bevy plugin"

      - name: build front
        run: |
          cd jornet-server-ui
          npm install
          npm run build
          cp -r build ../static
          git add ../static
          git commit --message "Built front"

      - name: push branch
        run: |
          git push --force origin release-clever

      - uses: 47ng/actions-clever-cloud@v1.2.0
        with:
          appID: app_451f9750-246e-4649-b419-7f3888fa2c69
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
