name: Server Release

on:
  push:
    tags:        
      - jornet-server-v**

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git checkout -b release-clever
          
      - name: build front
        run: |
          cd jornet-server-ui
          npm install
          npm run build
          cp -r build/ ../jornet-server/static/
          cd ..

      - name: push branch
        run: |
          git rm jornet-server/static/.gitignore
          git add jornet-server/static
          git commit --message "Built front"
          git push --force origin release-clever

      - uses: 47ng/actions-clever-cloud@848b643ba0771c980a3cefb7e59918dedd2d6fef
        with:
          appID: app_451f9750-246e-4649-b419-7f3888fa2c69
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
