name: Server Release

on:
  push:
    tags:        
      - jornet-server-v**

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup git
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git checkout -b release-clever
          
      - name: remove Bevy plugin
        run: |
          rm -rf bevy-jornet
          cargo new --lib bevy-jornet
          git add bevy-jornet
          git commit --message "remove Bevy plugin"

      - name: build front
        run: |
          cd jornet-server-ui
          npm install
          npm run build
          cp -r build ../static
          git add static
          git commit --message "Built front"

      - name: push branch
        run: |
          git push --force origin release-clever

      - uses: 47ng/actions-clever-cloud@v1.2.0
        with:
          appID: app_451f9750-246e-4649-b419-7f3888fa2c69
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
